version: "3.9"
services:
  database-backend:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
  mongo-backend:
    image: "bitnami/mongodb"
    ports:
      - "27017:27017"
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongo
      MONGODB_ROOT_PASSWORD: mongo
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"